#服务端配置
server:
  port: 8086
  servlet:
    context-path: /api/zblog  #添加接口api


#数据库配置
spring:
  #生产环境配置
  profiles:
    active: dev

#开启热部署
    devtools:
      restart:
        enabled: true  #设置开启热部署
        additional-paths: src/main/java #重启目录
        exclude: WEB-INF/**
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效
  cache:
    #redis 配置
    redis:
      database: 1
      host: localhost
      port: 6379
      password: ''
      lettuce:
        pool:
          max-active: 8   #最大连接数据库连接数,设 0 为没有限制
          max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
          max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
          min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
        shutdown-timeout: 100ms

mybatis-plus:
  mapper-locations: classpath:/resources/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.ityihang.zblog.**.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

yihang:
  shiro:
    excludeUrls: /sys/login,/sys/randomImage

# Logger Config
logging:
  level:
    cn.ityihang.zblog.*.mapper: debug

# ===================================
# 分布式文件系统FDFS配置
# ===================================
# 连接超时时间
fdfs:
  connect-timeout: 600
  # 读取超时时间
  so-timeout: 1500
  # 缩略图的宽高
  thumb-image.height: 150
  thumb-image.width: 150
  # tracker服务配置地址列表，替换成自己服务的IP地址，支持多个 端口：22122/23000
  tracker-list: localhost:22122
  pool.jmx-enabled: false
